// source: template.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.data.Template');
goog.provide('proto.rv.data.Template.Document');
goog.provide('proto.rv.data.Template.Slide');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rv.data.Action');
goog.require('proto.rv.data.ApplicationInfo');
goog.require('proto.rv.data.Slide');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.Template = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.Template, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.Template.displayName = 'proto.rv.data.Template';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.Template.Slide = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rv.data.Template.Slide.repeatedFields_, null);
};
goog.inherits(proto.rv.data.Template.Slide, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.Template.Slide.displayName = 'proto.rv.data.Template.Slide';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.Template.Document = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rv.data.Template.Document.repeatedFields_, null);
};
goog.inherits(proto.rv.data.Template.Document, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.Template.Document.displayName = 'proto.rv.data.Template.Document';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.Template.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.Template.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.Template} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.Template.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.Template}
 */
proto.rv.data.Template.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.Template;
  return proto.rv.data.Template.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.Template} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.Template}
 */
proto.rv.data.Template.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.Template.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.Template.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.Template} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.Template.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rv.data.Template.Slide.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.Template.Slide.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.Template.Slide.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.Template.Slide} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.Template.Slide.toObject = function(includeInstance, msg) {
  var f, obj = {
baseSlide: (f = msg.getBaseSlide()) && proto.rv.data.Slide.toObject(includeInstance, f),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
actionsList: jspb.Message.toObjectList(msg.getActionsList(),
    proto.rv.data.Action.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.Template.Slide}
 */
proto.rv.data.Template.Slide.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.Template.Slide;
  return proto.rv.data.Template.Slide.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.Template.Slide} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.Template.Slide}
 */
proto.rv.data.Template.Slide.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.Slide;
      reader.readMessage(value,proto.rv.data.Slide.deserializeBinaryFromReader);
      msg.setBaseSlide(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.rv.data.Action;
      reader.readMessage(value,proto.rv.data.Action.deserializeBinaryFromReader);
      msg.addActions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.Template.Slide.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.Template.Slide.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.Template.Slide} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.Template.Slide.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBaseSlide();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.Slide.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getActionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.rv.data.Action.serializeBinaryToWriter
    );
  }
};


/**
 * optional Slide base_slide = 1;
 * @return {?proto.rv.data.Slide}
 */
proto.rv.data.Template.Slide.prototype.getBaseSlide = function() {
  return /** @type{?proto.rv.data.Slide} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.Slide, 1));
};


/**
 * @param {?proto.rv.data.Slide|undefined} value
 * @return {!proto.rv.data.Template.Slide} returns this
*/
proto.rv.data.Template.Slide.prototype.setBaseSlide = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.Template.Slide} returns this
 */
proto.rv.data.Template.Slide.prototype.clearBaseSlide = function() {
  return this.setBaseSlide(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.Template.Slide.prototype.hasBaseSlide = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.rv.data.Template.Slide.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.rv.data.Template.Slide} returns this
 */
proto.rv.data.Template.Slide.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Action actions = 3;
 * @return {!Array<!proto.rv.data.Action>}
 */
proto.rv.data.Template.Slide.prototype.getActionsList = function() {
  return /** @type{!Array<!proto.rv.data.Action>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rv.data.Action, 3));
};


/**
 * @param {!Array<!proto.rv.data.Action>} value
 * @return {!proto.rv.data.Template.Slide} returns this
*/
proto.rv.data.Template.Slide.prototype.setActionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.rv.data.Action=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rv.data.Action}
 */
proto.rv.data.Template.Slide.prototype.addActions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.rv.data.Action, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rv.data.Template.Slide} returns this
 */
proto.rv.data.Template.Slide.prototype.clearActionsList = function() {
  return this.setActionsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rv.data.Template.Document.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.Template.Document.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.Template.Document.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.Template.Document} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.Template.Document.toObject = function(includeInstance, msg) {
  var f, obj = {
applicationInfo: (f = msg.getApplicationInfo()) && proto.rv.data.ApplicationInfo.toObject(includeInstance, f),
slidesList: jspb.Message.toObjectList(msg.getSlidesList(),
    proto.rv.data.Template.Slide.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.Template.Document}
 */
proto.rv.data.Template.Document.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.Template.Document;
  return proto.rv.data.Template.Document.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.Template.Document} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.Template.Document}
 */
proto.rv.data.Template.Document.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.ApplicationInfo;
      reader.readMessage(value,proto.rv.data.ApplicationInfo.deserializeBinaryFromReader);
      msg.setApplicationInfo(value);
      break;
    case 3:
      var value = new proto.rv.data.Template.Slide;
      reader.readMessage(value,proto.rv.data.Template.Slide.deserializeBinaryFromReader);
      msg.addSlides(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.Template.Document.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.Template.Document.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.Template.Document} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.Template.Document.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApplicationInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.ApplicationInfo.serializeBinaryToWriter
    );
  }
  f = message.getSlidesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.rv.data.Template.Slide.serializeBinaryToWriter
    );
  }
};


/**
 * optional ApplicationInfo application_info = 1;
 * @return {?proto.rv.data.ApplicationInfo}
 */
proto.rv.data.Template.Document.prototype.getApplicationInfo = function() {
  return /** @type{?proto.rv.data.ApplicationInfo} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.ApplicationInfo, 1));
};


/**
 * @param {?proto.rv.data.ApplicationInfo|undefined} value
 * @return {!proto.rv.data.Template.Document} returns this
*/
proto.rv.data.Template.Document.prototype.setApplicationInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.Template.Document} returns this
 */
proto.rv.data.Template.Document.prototype.clearApplicationInfo = function() {
  return this.setApplicationInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.Template.Document.prototype.hasApplicationInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Slide slides = 3;
 * @return {!Array<!proto.rv.data.Template.Slide>}
 */
proto.rv.data.Template.Document.prototype.getSlidesList = function() {
  return /** @type{!Array<!proto.rv.data.Template.Slide>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rv.data.Template.Slide, 3));
};


/**
 * @param {!Array<!proto.rv.data.Template.Slide>} value
 * @return {!proto.rv.data.Template.Document} returns this
*/
proto.rv.data.Template.Document.prototype.setSlidesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.rv.data.Template.Slide=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rv.data.Template.Slide}
 */
proto.rv.data.Template.Document.prototype.addSlides = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.rv.data.Template.Slide, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rv.data.Template.Document} returns this
 */
proto.rv.data.Template.Document.prototype.clearSlidesList = function() {
  return this.setSlidesList([]);
};


