// source: rv2d.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.data.TextLayer');
goog.provide('proto.rv.data.TextLayer.Composite');
goog.provide('proto.rv.data.TextLayer.LayertypeCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rv.data.Graphics.BackgroundEffect');
goog.require('proto.rv.data.Graphics.Text.CutOutFill');
goog.require('proto.rv.data.Media');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.TextLayer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rv.data.TextLayer.oneofGroups_);
};
goog.inherits(proto.rv.data.TextLayer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.TextLayer.displayName = 'proto.rv.data.TextLayer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.TextLayer.Composite = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.TextLayer.Composite, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.TextLayer.Composite.displayName = 'proto.rv.data.TextLayer.Composite';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rv.data.TextLayer.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.rv.data.TextLayer.LayertypeCase = {
  LAYERTYPE_NOT_SET: 0,
  COMPOSITE: 1,
  MEDIA: 2,
  CUT_OUT: 3,
  BACKGROUND_EFFECT: 4
};

/**
 * @return {proto.rv.data.TextLayer.LayertypeCase}
 */
proto.rv.data.TextLayer.prototype.getLayertypeCase = function() {
  return /** @type {proto.rv.data.TextLayer.LayertypeCase} */(jspb.Message.computeOneofCase(this, proto.rv.data.TextLayer.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.TextLayer.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.TextLayer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.TextLayer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.TextLayer.toObject = function(includeInstance, msg) {
  var f, obj = {
composite: (f = msg.getComposite()) && proto.rv.data.TextLayer.Composite.toObject(includeInstance, f),
media: (f = msg.getMedia()) && proto.rv.data.Media.toObject(includeInstance, f),
cutOut: (f = msg.getCutOut()) && proto.rv.data.Graphics.Text.CutOutFill.toObject(includeInstance, f),
backgroundEffect: (f = msg.getBackgroundEffect()) && proto.rv.data.Graphics.BackgroundEffect.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.TextLayer}
 */
proto.rv.data.TextLayer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.TextLayer;
  return proto.rv.data.TextLayer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.TextLayer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.TextLayer}
 */
proto.rv.data.TextLayer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.TextLayer.Composite;
      reader.readMessage(value,proto.rv.data.TextLayer.Composite.deserializeBinaryFromReader);
      msg.setComposite(value);
      break;
    case 2:
      var value = new proto.rv.data.Media;
      reader.readMessage(value,proto.rv.data.Media.deserializeBinaryFromReader);
      msg.setMedia(value);
      break;
    case 3:
      var value = new proto.rv.data.Graphics.Text.CutOutFill;
      reader.readMessage(value,proto.rv.data.Graphics.Text.CutOutFill.deserializeBinaryFromReader);
      msg.setCutOut(value);
      break;
    case 4:
      var value = new proto.rv.data.Graphics.BackgroundEffect;
      reader.readMessage(value,proto.rv.data.Graphics.BackgroundEffect.deserializeBinaryFromReader);
      msg.setBackgroundEffect(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.TextLayer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.TextLayer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.TextLayer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.TextLayer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComposite();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.TextLayer.Composite.serializeBinaryToWriter
    );
  }
  f = message.getMedia();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.rv.data.Media.serializeBinaryToWriter
    );
  }
  f = message.getCutOut();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.rv.data.Graphics.Text.CutOutFill.serializeBinaryToWriter
    );
  }
  f = message.getBackgroundEffect();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.rv.data.Graphics.BackgroundEffect.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.TextLayer.Composite.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.TextLayer.Composite.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.TextLayer.Composite} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.TextLayer.Composite.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.TextLayer.Composite}
 */
proto.rv.data.TextLayer.Composite.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.TextLayer.Composite;
  return proto.rv.data.TextLayer.Composite.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.TextLayer.Composite} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.TextLayer.Composite}
 */
proto.rv.data.TextLayer.Composite.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.TextLayer.Composite.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.TextLayer.Composite.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.TextLayer.Composite} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.TextLayer.Composite.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * optional Composite composite = 1;
 * @return {?proto.rv.data.TextLayer.Composite}
 */
proto.rv.data.TextLayer.prototype.getComposite = function() {
  return /** @type{?proto.rv.data.TextLayer.Composite} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.TextLayer.Composite, 1));
};


/**
 * @param {?proto.rv.data.TextLayer.Composite|undefined} value
 * @return {!proto.rv.data.TextLayer} returns this
*/
proto.rv.data.TextLayer.prototype.setComposite = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.rv.data.TextLayer.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.TextLayer} returns this
 */
proto.rv.data.TextLayer.prototype.clearComposite = function() {
  return this.setComposite(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.TextLayer.prototype.hasComposite = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Media media = 2;
 * @return {?proto.rv.data.Media}
 */
proto.rv.data.TextLayer.prototype.getMedia = function() {
  return /** @type{?proto.rv.data.Media} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.Media, 2));
};


/**
 * @param {?proto.rv.data.Media|undefined} value
 * @return {!proto.rv.data.TextLayer} returns this
*/
proto.rv.data.TextLayer.prototype.setMedia = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.rv.data.TextLayer.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.TextLayer} returns this
 */
proto.rv.data.TextLayer.prototype.clearMedia = function() {
  return this.setMedia(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.TextLayer.prototype.hasMedia = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Graphics.Text.CutOutFill cut_out = 3;
 * @return {?proto.rv.data.Graphics.Text.CutOutFill}
 */
proto.rv.data.TextLayer.prototype.getCutOut = function() {
  return /** @type{?proto.rv.data.Graphics.Text.CutOutFill} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.Graphics.Text.CutOutFill, 3));
};


/**
 * @param {?proto.rv.data.Graphics.Text.CutOutFill|undefined} value
 * @return {!proto.rv.data.TextLayer} returns this
*/
proto.rv.data.TextLayer.prototype.setCutOut = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.rv.data.TextLayer.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.TextLayer} returns this
 */
proto.rv.data.TextLayer.prototype.clearCutOut = function() {
  return this.setCutOut(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.TextLayer.prototype.hasCutOut = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Graphics.BackgroundEffect background_effect = 4;
 * @return {?proto.rv.data.Graphics.BackgroundEffect}
 */
proto.rv.data.TextLayer.prototype.getBackgroundEffect = function() {
  return /** @type{?proto.rv.data.Graphics.BackgroundEffect} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.Graphics.BackgroundEffect, 4));
};


/**
 * @param {?proto.rv.data.Graphics.BackgroundEffect|undefined} value
 * @return {!proto.rv.data.TextLayer} returns this
*/
proto.rv.data.TextLayer.prototype.setBackgroundEffect = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.rv.data.TextLayer.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.TextLayer} returns this
 */
proto.rv.data.TextLayer.prototype.clearBackgroundEffect = function() {
  return this.setBackgroundEffect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.TextLayer.prototype.hasBackgroundEffect = function() {
  return jspb.Message.getField(this, 4) != null;
};


