// source: proApiV1Looks.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.data.API_v1_Screen');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Screen = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Screen, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Screen.displayName = 'proto.rv.data.API_v1_Screen';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Screen.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Screen.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Screen} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Screen.toObject = function(includeInstance, msg) {
  var f, obj = {
videoInput: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
media: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
slide: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
announcements: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
props: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
messages: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
presentation: jspb.Message.getFieldWithDefault(msg, 7, ""),
mask: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Screen}
 */
proto.rv.data.API_v1_Screen.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Screen;
  return proto.rv.data.API_v1_Screen.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Screen} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Screen}
 */
proto.rv.data.API_v1_Screen.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVideoInput(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMedia(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSlide(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAnnouncements(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProps(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMessages(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPresentation(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setMask(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Screen.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Screen.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Screen} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Screen.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVideoInput();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMedia();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getSlide();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getAnnouncements();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getProps();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getMessages();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getPresentation();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getMask();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional bool video_input = 1;
 * @return {boolean}
 */
proto.rv.data.API_v1_Screen.prototype.getVideoInput = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setVideoInput = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool media = 2;
 * @return {boolean}
 */
proto.rv.data.API_v1_Screen.prototype.getMedia = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setMedia = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool slide = 3;
 * @return {boolean}
 */
proto.rv.data.API_v1_Screen.prototype.getSlide = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setSlide = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool announcements = 4;
 * @return {boolean}
 */
proto.rv.data.API_v1_Screen.prototype.getAnnouncements = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setAnnouncements = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool props = 5;
 * @return {boolean}
 */
proto.rv.data.API_v1_Screen.prototype.getProps = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setProps = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool messages = 6;
 * @return {boolean}
 */
proto.rv.data.API_v1_Screen.prototype.getMessages = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setMessages = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string presentation = 7;
 * @return {string}
 */
proto.rv.data.API_v1_Screen.prototype.getPresentation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setPresentation = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string mask = 8;
 * @return {string}
 */
proto.rv.data.API_v1_Screen.prototype.getMask = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.rv.data.API_v1_Screen} returns this
 */
proto.rv.data.API_v1_Screen.prototype.setMask = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


