// source: analyticsSync.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.analytics.Sync');
goog.provide('proto.rv.analytics.Sync.Local');
goog.provide('proto.rv.analytics.Sync.Local.SyncType');
goog.provide('proto.rv.analytics.Sync.SynctypeCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.Sync = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rv.analytics.Sync.oneofGroups_);
};
goog.inherits(proto.rv.analytics.Sync, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.Sync.displayName = 'proto.rv.analytics.Sync';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.Sync.Local = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.analytics.Sync.Local, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.Sync.Local.displayName = 'proto.rv.analytics.Sync.Local';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rv.analytics.Sync.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.rv.analytics.Sync.SynctypeCase = {
  SYNCTYPE_NOT_SET: 0,
  LOCAL: 1
};

/**
 * @return {proto.rv.analytics.Sync.SynctypeCase}
 */
proto.rv.analytics.Sync.prototype.getSynctypeCase = function() {
  return /** @type {proto.rv.analytics.Sync.SynctypeCase} */(jspb.Message.computeOneofCase(this, proto.rv.analytics.Sync.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.Sync.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.Sync.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.Sync} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Sync.toObject = function(includeInstance, msg) {
  var f, obj = {
local: (f = msg.getLocal()) && proto.rv.analytics.Sync.Local.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.Sync}
 */
proto.rv.analytics.Sync.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.Sync;
  return proto.rv.analytics.Sync.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.Sync} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.Sync}
 */
proto.rv.analytics.Sync.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.analytics.Sync.Local;
      reader.readMessage(value,proto.rv.analytics.Sync.Local.deserializeBinaryFromReader);
      msg.setLocal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.Sync.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.Sync.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.Sync} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Sync.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocal();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.analytics.Sync.Local.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.Sync.Local.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.Sync.Local.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.Sync.Local} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Sync.Local.toObject = function(includeInstance, msg) {
  var f, obj = {
syncType: jspb.Message.getFieldWithDefault(msg, 1, 0),
includeLibrary: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
includeMedia: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
includePlaylists: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
includeThemes: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
includeSupportFiles: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
replaceFiles: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.Sync.Local}
 */
proto.rv.analytics.Sync.Local.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.Sync.Local;
  return proto.rv.analytics.Sync.Local.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.Sync.Local} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.Sync.Local}
 */
proto.rv.analytics.Sync.Local.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.rv.analytics.Sync.Local.SyncType} */ (reader.readEnum());
      msg.setSyncType(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeLibrary(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeMedia(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludePlaylists(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeThemes(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeSupportFiles(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReplaceFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.Sync.Local.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.Sync.Local.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.Sync.Local} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Sync.Local.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSyncType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getIncludeLibrary();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getIncludeMedia();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getIncludePlaylists();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getIncludeThemes();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getIncludeSupportFiles();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getReplaceFiles();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.rv.analytics.Sync.Local.SyncType = {
  SYNC_TYPE_UP: 0,
  SYNC_TYPE_DOWN: 1
};

/**
 * optional SyncType sync_type = 1;
 * @return {!proto.rv.analytics.Sync.Local.SyncType}
 */
proto.rv.analytics.Sync.Local.prototype.getSyncType = function() {
  return /** @type {!proto.rv.analytics.Sync.Local.SyncType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.rv.analytics.Sync.Local.SyncType} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setSyncType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool include_library = 2;
 * @return {boolean}
 */
proto.rv.analytics.Sync.Local.prototype.getIncludeLibrary = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setIncludeLibrary = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool include_media = 3;
 * @return {boolean}
 */
proto.rv.analytics.Sync.Local.prototype.getIncludeMedia = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setIncludeMedia = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool include_playlists = 4;
 * @return {boolean}
 */
proto.rv.analytics.Sync.Local.prototype.getIncludePlaylists = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setIncludePlaylists = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool include_themes = 5;
 * @return {boolean}
 */
proto.rv.analytics.Sync.Local.prototype.getIncludeThemes = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setIncludeThemes = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool include_support_files = 6;
 * @return {boolean}
 */
proto.rv.analytics.Sync.Local.prototype.getIncludeSupportFiles = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setIncludeSupportFiles = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool replace_files = 7;
 * @return {boolean}
 */
proto.rv.analytics.Sync.Local.prototype.getReplaceFiles = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.Sync.Local} returns this
 */
proto.rv.analytics.Sync.Local.prototype.setReplaceFiles = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional Local local = 1;
 * @return {?proto.rv.analytics.Sync.Local}
 */
proto.rv.analytics.Sync.prototype.getLocal = function() {
  return /** @type{?proto.rv.analytics.Sync.Local} */ (
    jspb.Message.getWrapperField(this, proto.rv.analytics.Sync.Local, 1));
};


/**
 * @param {?proto.rv.analytics.Sync.Local|undefined} value
 * @return {!proto.rv.analytics.Sync} returns this
*/
proto.rv.analytics.Sync.prototype.setLocal = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.rv.analytics.Sync.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.analytics.Sync} returns this
 */
proto.rv.analytics.Sync.prototype.clearLocal = function() {
  return this.setLocal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.analytics.Sync.prototype.hasLocal = function() {
  return jspb.Message.getField(this, 1) != null;
};


