// source: proCore.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.data.TimerStateUpdate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rv.data.Timer');
goog.require('proto.rv.data.TimerRuntimeState');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.TimerStateUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.TimerStateUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.TimerStateUpdate.displayName = 'proto.rv.data.TimerStateUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.TimerStateUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.TimerStateUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.TimerStateUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.TimerStateUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
timer: (f = msg.getTimer()) && proto.rv.data.Timer.toObject(includeInstance, f),
state: (f = msg.getState()) && proto.rv.data.TimerRuntimeState.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.TimerStateUpdate}
 */
proto.rv.data.TimerStateUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.TimerStateUpdate;
  return proto.rv.data.TimerStateUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.TimerStateUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.TimerStateUpdate}
 */
proto.rv.data.TimerStateUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.Timer;
      reader.readMessage(value,proto.rv.data.Timer.deserializeBinaryFromReader);
      msg.setTimer(value);
      break;
    case 2:
      var value = new proto.rv.data.TimerRuntimeState;
      reader.readMessage(value,proto.rv.data.TimerRuntimeState.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.TimerStateUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.TimerStateUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.TimerStateUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.TimerStateUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.Timer.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.rv.data.TimerRuntimeState.serializeBinaryToWriter
    );
  }
};


/**
 * optional Timer timer = 1;
 * @return {?proto.rv.data.Timer}
 */
proto.rv.data.TimerStateUpdate.prototype.getTimer = function() {
  return /** @type{?proto.rv.data.Timer} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.Timer, 1));
};


/**
 * @param {?proto.rv.data.Timer|undefined} value
 * @return {!proto.rv.data.TimerStateUpdate} returns this
*/
proto.rv.data.TimerStateUpdate.prototype.setTimer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.TimerStateUpdate} returns this
 */
proto.rv.data.TimerStateUpdate.prototype.clearTimer = function() {
  return this.setTimer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.TimerStateUpdate.prototype.hasTimer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TimerRuntimeState state = 2;
 * @return {?proto.rv.data.TimerRuntimeState}
 */
proto.rv.data.TimerStateUpdate.prototype.getState = function() {
  return /** @type{?proto.rv.data.TimerRuntimeState} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.TimerRuntimeState, 2));
};


/**
 * @param {?proto.rv.data.TimerRuntimeState|undefined} value
 * @return {!proto.rv.data.TimerStateUpdate} returns this
*/
proto.rv.data.TimerStateUpdate.prototype.setState = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.TimerStateUpdate} returns this
 */
proto.rv.data.TimerStateUpdate.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.TimerStateUpdate.prototype.hasState = function() {
  return jspb.Message.getField(this, 2) != null;
};


