// source: proApiV1Message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.data.API_v1_Message_Response');
goog.provide('proto.rv.data.API_v1_Message_Response.ClearMessage');
goog.provide('proto.rv.data.API_v1_Message_Response.CreateMessage');
goog.provide('proto.rv.data.API_v1_Message_Response.DeleteMessage');
goog.provide('proto.rv.data.API_v1_Message_Response.GetMessage');
goog.provide('proto.rv.data.API_v1_Message_Response.Messages');
goog.provide('proto.rv.data.API_v1_Message_Response.PutMessage');
goog.provide('proto.rv.data.API_v1_Message_Response.ResponseCase');
goog.provide('proto.rv.data.API_v1_Message_Response.TriggerMessage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rv.data.API_v1_Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rv.data.API_v1_Message_Response.oneofGroups_);
};
goog.inherits(proto.rv.data.API_v1_Message_Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.displayName = 'proto.rv.data.API_v1_Message_Response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.Messages = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rv.data.API_v1_Message_Response.Messages.repeatedFields_, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.Messages, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.Messages.displayName = 'proto.rv.data.API_v1_Message_Response.Messages';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.CreateMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.CreateMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.CreateMessage.displayName = 'proto.rv.data.API_v1_Message_Response.CreateMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.GetMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.GetMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.GetMessage.displayName = 'proto.rv.data.API_v1_Message_Response.GetMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.PutMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.PutMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.PutMessage.displayName = 'proto.rv.data.API_v1_Message_Response.PutMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.DeleteMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.DeleteMessage.displayName = 'proto.rv.data.API_v1_Message_Response.DeleteMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.TriggerMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.TriggerMessage.displayName = 'proto.rv.data.API_v1_Message_Response.TriggerMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_Message_Response.ClearMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_Message_Response.ClearMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_Message_Response.ClearMessage.displayName = 'proto.rv.data.API_v1_Message_Response.ClearMessage';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rv.data.API_v1_Message_Response.oneofGroups_ = [[1,2,3,4,5,6,7]];

/**
 * @enum {number}
 */
proto.rv.data.API_v1_Message_Response.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  MESSAGES: 1,
  CREATE_MESSAGE: 2,
  GET_MESSAGE: 3,
  PUT_MESSAGE: 4,
  DELETE_MESSAGE: 5,
  TRIGGER_MESSAGE: 6,
  CLEAR_MESSAGE: 7
};

/**
 * @return {proto.rv.data.API_v1_Message_Response.ResponseCase}
 */
proto.rv.data.API_v1_Message_Response.prototype.getResponseCase = function() {
  return /** @type {proto.rv.data.API_v1_Message_Response.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.rv.data.API_v1_Message_Response.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.toObject = function(includeInstance, msg) {
  var f, obj = {
messages: (f = msg.getMessages()) && proto.rv.data.API_v1_Message_Response.Messages.toObject(includeInstance, f),
createMessage: (f = msg.getCreateMessage()) && proto.rv.data.API_v1_Message_Response.CreateMessage.toObject(includeInstance, f),
getMessage: (f = msg.getGetMessage()) && proto.rv.data.API_v1_Message_Response.GetMessage.toObject(includeInstance, f),
putMessage: (f = msg.getPutMessage()) && proto.rv.data.API_v1_Message_Response.PutMessage.toObject(includeInstance, f),
deleteMessage: (f = msg.getDeleteMessage()) && proto.rv.data.API_v1_Message_Response.DeleteMessage.toObject(includeInstance, f),
triggerMessage: (f = msg.getTriggerMessage()) && proto.rv.data.API_v1_Message_Response.TriggerMessage.toObject(includeInstance, f),
clearMessage: (f = msg.getClearMessage()) && proto.rv.data.API_v1_Message_Response.ClearMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response}
 */
proto.rv.data.API_v1_Message_Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response;
  return proto.rv.data.API_v1_Message_Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response}
 */
proto.rv.data.API_v1_Message_Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.API_v1_Message_Response.Messages;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.Messages.deserializeBinaryFromReader);
      msg.setMessages(value);
      break;
    case 2:
      var value = new proto.rv.data.API_v1_Message_Response.CreateMessage;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.CreateMessage.deserializeBinaryFromReader);
      msg.setCreateMessage(value);
      break;
    case 3:
      var value = new proto.rv.data.API_v1_Message_Response.GetMessage;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.GetMessage.deserializeBinaryFromReader);
      msg.setGetMessage(value);
      break;
    case 4:
      var value = new proto.rv.data.API_v1_Message_Response.PutMessage;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.PutMessage.deserializeBinaryFromReader);
      msg.setPutMessage(value);
      break;
    case 5:
      var value = new proto.rv.data.API_v1_Message_Response.DeleteMessage;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.DeleteMessage.deserializeBinaryFromReader);
      msg.setDeleteMessage(value);
      break;
    case 6:
      var value = new proto.rv.data.API_v1_Message_Response.TriggerMessage;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.TriggerMessage.deserializeBinaryFromReader);
      msg.setTriggerMessage(value);
      break;
    case 7:
      var value = new proto.rv.data.API_v1_Message_Response.ClearMessage;
      reader.readMessage(value,proto.rv.data.API_v1_Message_Response.ClearMessage.deserializeBinaryFromReader);
      msg.setClearMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessages();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.API_v1_Message_Response.Messages.serializeBinaryToWriter
    );
  }
  f = message.getCreateMessage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.rv.data.API_v1_Message_Response.CreateMessage.serializeBinaryToWriter
    );
  }
  f = message.getGetMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.rv.data.API_v1_Message_Response.GetMessage.serializeBinaryToWriter
    );
  }
  f = message.getPutMessage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.rv.data.API_v1_Message_Response.PutMessage.serializeBinaryToWriter
    );
  }
  f = message.getDeleteMessage();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.rv.data.API_v1_Message_Response.DeleteMessage.serializeBinaryToWriter
    );
  }
  f = message.getTriggerMessage();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.rv.data.API_v1_Message_Response.TriggerMessage.serializeBinaryToWriter
    );
  }
  f = message.getClearMessage();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.rv.data.API_v1_Message_Response.ClearMessage.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rv.data.API_v1_Message_Response.Messages.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.Messages.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.Messages.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.Messages} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.Messages.toObject = function(includeInstance, msg) {
  var f, obj = {
messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    proto.rv.data.API_v1_Message.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.Messages}
 */
proto.rv.data.API_v1_Message_Response.Messages.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.Messages;
  return proto.rv.data.API_v1_Message_Response.Messages.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.Messages} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.Messages}
 */
proto.rv.data.API_v1_Message_Response.Messages.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.API_v1_Message;
      reader.readMessage(value,proto.rv.data.API_v1_Message.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.Messages.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.Messages.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.Messages} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.Messages.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.rv.data.API_v1_Message.serializeBinaryToWriter
    );
  }
};


/**
 * repeated API_v1_Message messages = 1;
 * @return {!Array<!proto.rv.data.API_v1_Message>}
 */
proto.rv.data.API_v1_Message_Response.Messages.prototype.getMessagesList = function() {
  return /** @type{!Array<!proto.rv.data.API_v1_Message>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rv.data.API_v1_Message, 1));
};


/**
 * @param {!Array<!proto.rv.data.API_v1_Message>} value
 * @return {!proto.rv.data.API_v1_Message_Response.Messages} returns this
*/
proto.rv.data.API_v1_Message_Response.Messages.prototype.setMessagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.rv.data.API_v1_Message=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rv.data.API_v1_Message}
 */
proto.rv.data.API_v1_Message_Response.Messages.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.rv.data.API_v1_Message, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rv.data.API_v1_Message_Response.Messages} returns this
 */
proto.rv.data.API_v1_Message_Response.Messages.prototype.clearMessagesList = function() {
  return this.setMessagesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.CreateMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.CreateMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
message: (f = msg.getMessage()) && proto.rv.data.API_v1_Message.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.CreateMessage}
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.CreateMessage;
  return proto.rv.data.API_v1_Message_Response.CreateMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.CreateMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.CreateMessage}
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.API_v1_Message;
      reader.readMessage(value,proto.rv.data.API_v1_Message.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.CreateMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.CreateMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.API_v1_Message.serializeBinaryToWriter
    );
  }
};


/**
 * optional API_v1_Message message = 1;
 * @return {?proto.rv.data.API_v1_Message}
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.prototype.getMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message, 1));
};


/**
 * @param {?proto.rv.data.API_v1_Message|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response.CreateMessage} returns this
*/
proto.rv.data.API_v1_Message_Response.CreateMessage.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response.CreateMessage} returns this
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.CreateMessage.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.GetMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.GetMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.GetMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.GetMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
message: (f = msg.getMessage()) && proto.rv.data.API_v1_Message.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.GetMessage}
 */
proto.rv.data.API_v1_Message_Response.GetMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.GetMessage;
  return proto.rv.data.API_v1_Message_Response.GetMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.GetMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.GetMessage}
 */
proto.rv.data.API_v1_Message_Response.GetMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.API_v1_Message;
      reader.readMessage(value,proto.rv.data.API_v1_Message.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.GetMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.GetMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.GetMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.GetMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.API_v1_Message.serializeBinaryToWriter
    );
  }
};


/**
 * optional API_v1_Message message = 1;
 * @return {?proto.rv.data.API_v1_Message}
 */
proto.rv.data.API_v1_Message_Response.GetMessage.prototype.getMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message, 1));
};


/**
 * @param {?proto.rv.data.API_v1_Message|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response.GetMessage} returns this
*/
proto.rv.data.API_v1_Message_Response.GetMessage.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response.GetMessage} returns this
 */
proto.rv.data.API_v1_Message_Response.GetMessage.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.GetMessage.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.PutMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.PutMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.PutMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.PutMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
message: (f = msg.getMessage()) && proto.rv.data.API_v1_Message.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.PutMessage}
 */
proto.rv.data.API_v1_Message_Response.PutMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.PutMessage;
  return proto.rv.data.API_v1_Message_Response.PutMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.PutMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.PutMessage}
 */
proto.rv.data.API_v1_Message_Response.PutMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.data.API_v1_Message;
      reader.readMessage(value,proto.rv.data.API_v1_Message.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.PutMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.PutMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.PutMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.PutMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.data.API_v1_Message.serializeBinaryToWriter
    );
  }
};


/**
 * optional API_v1_Message message = 1;
 * @return {?proto.rv.data.API_v1_Message}
 */
proto.rv.data.API_v1_Message_Response.PutMessage.prototype.getMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message, 1));
};


/**
 * @param {?proto.rv.data.API_v1_Message|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response.PutMessage} returns this
*/
proto.rv.data.API_v1_Message_Response.PutMessage.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response.PutMessage} returns this
 */
proto.rv.data.API_v1_Message_Response.PutMessage.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.PutMessage.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.DeleteMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.DeleteMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.DeleteMessage}
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.DeleteMessage;
  return proto.rv.data.API_v1_Message_Response.DeleteMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.DeleteMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.DeleteMessage}
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.DeleteMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.DeleteMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.DeleteMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.TriggerMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.TriggerMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.TriggerMessage}
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.TriggerMessage;
  return proto.rv.data.API_v1_Message_Response.TriggerMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.TriggerMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.TriggerMessage}
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.TriggerMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.TriggerMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.TriggerMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_Message_Response.ClearMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_Message_Response.ClearMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_Message_Response.ClearMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.ClearMessage.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_Message_Response.ClearMessage}
 */
proto.rv.data.API_v1_Message_Response.ClearMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_Message_Response.ClearMessage;
  return proto.rv.data.API_v1_Message_Response.ClearMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_Message_Response.ClearMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_Message_Response.ClearMessage}
 */
proto.rv.data.API_v1_Message_Response.ClearMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_Message_Response.ClearMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_Message_Response.ClearMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_Message_Response.ClearMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_Message_Response.ClearMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * optional Messages messages = 1;
 * @return {?proto.rv.data.API_v1_Message_Response.Messages}
 */
proto.rv.data.API_v1_Message_Response.prototype.getMessages = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.Messages} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.Messages, 1));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.Messages|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setMessages = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearMessages = function() {
  return this.setMessages(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasMessages = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CreateMessage create_message = 2;
 * @return {?proto.rv.data.API_v1_Message_Response.CreateMessage}
 */
proto.rv.data.API_v1_Message_Response.prototype.getCreateMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.CreateMessage} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.CreateMessage, 2));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.CreateMessage|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setCreateMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearCreateMessage = function() {
  return this.setCreateMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasCreateMessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GetMessage get_message = 3;
 * @return {?proto.rv.data.API_v1_Message_Response.GetMessage}
 */
proto.rv.data.API_v1_Message_Response.prototype.getGetMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.GetMessage} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.GetMessage, 3));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.GetMessage|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setGetMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearGetMessage = function() {
  return this.setGetMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasGetMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PutMessage put_message = 4;
 * @return {?proto.rv.data.API_v1_Message_Response.PutMessage}
 */
proto.rv.data.API_v1_Message_Response.prototype.getPutMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.PutMessage} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.PutMessage, 4));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.PutMessage|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setPutMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearPutMessage = function() {
  return this.setPutMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasPutMessage = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional DeleteMessage delete_message = 5;
 * @return {?proto.rv.data.API_v1_Message_Response.DeleteMessage}
 */
proto.rv.data.API_v1_Message_Response.prototype.getDeleteMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.DeleteMessage} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.DeleteMessage, 5));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.DeleteMessage|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setDeleteMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearDeleteMessage = function() {
  return this.setDeleteMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasDeleteMessage = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional TriggerMessage trigger_message = 6;
 * @return {?proto.rv.data.API_v1_Message_Response.TriggerMessage}
 */
proto.rv.data.API_v1_Message_Response.prototype.getTriggerMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.TriggerMessage} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.TriggerMessage, 6));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.TriggerMessage|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setTriggerMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearTriggerMessage = function() {
  return this.setTriggerMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasTriggerMessage = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ClearMessage clear_message = 7;
 * @return {?proto.rv.data.API_v1_Message_Response.ClearMessage}
 */
proto.rv.data.API_v1_Message_Response.prototype.getClearMessage = function() {
  return /** @type{?proto.rv.data.API_v1_Message_Response.ClearMessage} */ (
    jspb.Message.getWrapperField(this, proto.rv.data.API_v1_Message_Response.ClearMessage, 7));
};


/**
 * @param {?proto.rv.data.API_v1_Message_Response.ClearMessage|undefined} value
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
*/
proto.rv.data.API_v1_Message_Response.prototype.setClearMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.rv.data.API_v1_Message_Response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.data.API_v1_Message_Response} returns this
 */
proto.rv.data.API_v1_Message_Response.prototype.clearClearMessage = function() {
  return this.setClearMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.data.API_v1_Message_Response.prototype.hasClearMessage = function() {
  return jspb.Message.getField(this, 7) != null;
};


