// source: analyticsUpdate.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.analytics.Update');
goog.provide('proto.rv.analytics.Update.ActionCase');
goog.provide('proto.rv.analytics.Update.Downgrade');
goog.provide('proto.rv.analytics.Update.Downgrade.FromVersionType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.Update = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rv.analytics.Update.oneofGroups_);
};
goog.inherits(proto.rv.analytics.Update, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.Update.displayName = 'proto.rv.analytics.Update';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.Update.Downgrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.analytics.Update.Downgrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.Update.Downgrade.displayName = 'proto.rv.analytics.Update.Downgrade';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rv.analytics.Update.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.rv.analytics.Update.ActionCase = {
  ACTION_NOT_SET: 0,
  DOWNGRADE: 1
};

/**
 * @return {proto.rv.analytics.Update.ActionCase}
 */
proto.rv.analytics.Update.prototype.getActionCase = function() {
  return /** @type {proto.rv.analytics.Update.ActionCase} */(jspb.Message.computeOneofCase(this, proto.rv.analytics.Update.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.Update.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.Update.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.Update} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Update.toObject = function(includeInstance, msg) {
  var f, obj = {
downgrade: (f = msg.getDowngrade()) && proto.rv.analytics.Update.Downgrade.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.Update}
 */
proto.rv.analytics.Update.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.Update;
  return proto.rv.analytics.Update.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.Update} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.Update}
 */
proto.rv.analytics.Update.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.analytics.Update.Downgrade;
      reader.readMessage(value,proto.rv.analytics.Update.Downgrade.deserializeBinaryFromReader);
      msg.setDowngrade(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.Update.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.Update.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.Update} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Update.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDowngrade();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.analytics.Update.Downgrade.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.Update.Downgrade.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.Update.Downgrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.Update.Downgrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Update.Downgrade.toObject = function(includeInstance, msg) {
  var f, obj = {
fromVersionType: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.Update.Downgrade}
 */
proto.rv.analytics.Update.Downgrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.Update.Downgrade;
  return proto.rv.analytics.Update.Downgrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.Update.Downgrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.Update.Downgrade}
 */
proto.rv.analytics.Update.Downgrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.rv.analytics.Update.Downgrade.FromVersionType} */ (reader.readEnum());
      msg.setFromVersionType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.Update.Downgrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.Update.Downgrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.Update.Downgrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.Update.Downgrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromVersionType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.rv.analytics.Update.Downgrade.FromVersionType = {
  FROM_VERSION_TYPE_UNKNOWN: 0,
  FROM_VERSION_TYPE_BETA: 1,
  FROM_VERSION_TYPE_RELEASE: 2
};

/**
 * optional FromVersionType from_version_type = 1;
 * @return {!proto.rv.analytics.Update.Downgrade.FromVersionType}
 */
proto.rv.analytics.Update.Downgrade.prototype.getFromVersionType = function() {
  return /** @type {!proto.rv.analytics.Update.Downgrade.FromVersionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.rv.analytics.Update.Downgrade.FromVersionType} value
 * @return {!proto.rv.analytics.Update.Downgrade} returns this
 */
proto.rv.analytics.Update.Downgrade.prototype.setFromVersionType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Downgrade downgrade = 1;
 * @return {?proto.rv.analytics.Update.Downgrade}
 */
proto.rv.analytics.Update.prototype.getDowngrade = function() {
  return /** @type{?proto.rv.analytics.Update.Downgrade} */ (
    jspb.Message.getWrapperField(this, proto.rv.analytics.Update.Downgrade, 1));
};


/**
 * @param {?proto.rv.analytics.Update.Downgrade|undefined} value
 * @return {!proto.rv.analytics.Update} returns this
*/
proto.rv.analytics.Update.prototype.setDowngrade = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.rv.analytics.Update.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.analytics.Update} returns this
 */
proto.rv.analytics.Update.prototype.clearDowngrade = function() {
  return this.setDowngrade(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.analytics.Update.prototype.hasDowngrade = function() {
  return jspb.Message.getField(this, 1) != null;
};


