// source: analyticsProContent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.analytics.ProContent');
goog.provide('proto.rv.analytics.ProContent.Download');
goog.provide('proto.rv.analytics.ProContent.EventCase');
goog.provide('proto.rv.analytics.ProContent.ViewMediaBin');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.ProContent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rv.analytics.ProContent.oneofGroups_);
};
goog.inherits(proto.rv.analytics.ProContent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.ProContent.displayName = 'proto.rv.analytics.ProContent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.ProContent.ViewMediaBin = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.analytics.ProContent.ViewMediaBin, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.ProContent.ViewMediaBin.displayName = 'proto.rv.analytics.ProContent.ViewMediaBin';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.ProContent.Download = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.analytics.ProContent.Download, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.ProContent.Download.displayName = 'proto.rv.analytics.ProContent.Download';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rv.analytics.ProContent.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.rv.analytics.ProContent.EventCase = {
  EVENT_NOT_SET: 0,
  MEDIA_BIN: 1,
  DOWNLOAD: 2
};

/**
 * @return {proto.rv.analytics.ProContent.EventCase}
 */
proto.rv.analytics.ProContent.prototype.getEventCase = function() {
  return /** @type {proto.rv.analytics.ProContent.EventCase} */(jspb.Message.computeOneofCase(this, proto.rv.analytics.ProContent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.ProContent.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.ProContent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.ProContent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.ProContent.toObject = function(includeInstance, msg) {
  var f, obj = {
mediaBin: (f = msg.getMediaBin()) && proto.rv.analytics.ProContent.ViewMediaBin.toObject(includeInstance, f),
download: (f = msg.getDownload()) && proto.rv.analytics.ProContent.Download.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.ProContent}
 */
proto.rv.analytics.ProContent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.ProContent;
  return proto.rv.analytics.ProContent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.ProContent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.ProContent}
 */
proto.rv.analytics.ProContent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.analytics.ProContent.ViewMediaBin;
      reader.readMessage(value,proto.rv.analytics.ProContent.ViewMediaBin.deserializeBinaryFromReader);
      msg.setMediaBin(value);
      break;
    case 2:
      var value = new proto.rv.analytics.ProContent.Download;
      reader.readMessage(value,proto.rv.analytics.ProContent.Download.deserializeBinaryFromReader);
      msg.setDownload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.ProContent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.ProContent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.ProContent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.ProContent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMediaBin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.analytics.ProContent.ViewMediaBin.serializeBinaryToWriter
    );
  }
  f = message.getDownload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.rv.analytics.ProContent.Download.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.ProContent.ViewMediaBin.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.ProContent.ViewMediaBin.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.ProContent.ViewMediaBin} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.ProContent.ViewMediaBin.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.ProContent.ViewMediaBin}
 */
proto.rv.analytics.ProContent.ViewMediaBin.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.ProContent.ViewMediaBin;
  return proto.rv.analytics.ProContent.ViewMediaBin.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.ProContent.ViewMediaBin} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.ProContent.ViewMediaBin}
 */
proto.rv.analytics.ProContent.ViewMediaBin.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.ProContent.ViewMediaBin.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.ProContent.ViewMediaBin.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.ProContent.ViewMediaBin} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.ProContent.ViewMediaBin.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.ProContent.Download.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.ProContent.Download.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.ProContent.Download} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.ProContent.Download.toObject = function(includeInstance, msg) {
  var f, obj = {
isRetry: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.ProContent.Download}
 */
proto.rv.analytics.ProContent.Download.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.ProContent.Download;
  return proto.rv.analytics.ProContent.Download.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.ProContent.Download} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.ProContent.Download}
 */
proto.rv.analytics.ProContent.Download.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRetry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.ProContent.Download.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.ProContent.Download.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.ProContent.Download} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.ProContent.Download.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsRetry();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool is_retry = 1;
 * @return {boolean}
 */
proto.rv.analytics.ProContent.Download.prototype.getIsRetry = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rv.analytics.ProContent.Download} returns this
 */
proto.rv.analytics.ProContent.Download.prototype.setIsRetry = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional ViewMediaBin media_bin = 1;
 * @return {?proto.rv.analytics.ProContent.ViewMediaBin}
 */
proto.rv.analytics.ProContent.prototype.getMediaBin = function() {
  return /** @type{?proto.rv.analytics.ProContent.ViewMediaBin} */ (
    jspb.Message.getWrapperField(this, proto.rv.analytics.ProContent.ViewMediaBin, 1));
};


/**
 * @param {?proto.rv.analytics.ProContent.ViewMediaBin|undefined} value
 * @return {!proto.rv.analytics.ProContent} returns this
*/
proto.rv.analytics.ProContent.prototype.setMediaBin = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.rv.analytics.ProContent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.analytics.ProContent} returns this
 */
proto.rv.analytics.ProContent.prototype.clearMediaBin = function() {
  return this.setMediaBin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.analytics.ProContent.prototype.hasMediaBin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Download download = 2;
 * @return {?proto.rv.analytics.ProContent.Download}
 */
proto.rv.analytics.ProContent.prototype.getDownload = function() {
  return /** @type{?proto.rv.analytics.ProContent.Download} */ (
    jspb.Message.getWrapperField(this, proto.rv.analytics.ProContent.Download, 2));
};


/**
 * @param {?proto.rv.analytics.ProContent.Download|undefined} value
 * @return {!proto.rv.analytics.ProContent} returns this
*/
proto.rv.analytics.ProContent.prototype.setDownload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.rv.analytics.ProContent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.analytics.ProContent} returns this
 */
proto.rv.analytics.ProContent.prototype.clearDownload = function() {
  return this.setDownload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.analytics.ProContent.prototype.hasDownload = function() {
  return jspb.Message.getField(this, 2) != null;
};


