// source: analyticsPlaybackMarker.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.analytics.PlaybackMarker');
goog.provide('proto.rv.analytics.PlaybackMarker.CreateMarker');
goog.provide('proto.rv.analytics.PlaybackMarker.CreateMarker.Location');
goog.provide('proto.rv.analytics.PlaybackMarker.EventCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.PlaybackMarker = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rv.analytics.PlaybackMarker.oneofGroups_);
};
goog.inherits(proto.rv.analytics.PlaybackMarker, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.PlaybackMarker.displayName = 'proto.rv.analytics.PlaybackMarker';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.analytics.PlaybackMarker.CreateMarker = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.analytics.PlaybackMarker.CreateMarker, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.analytics.PlaybackMarker.CreateMarker.displayName = 'proto.rv.analytics.PlaybackMarker.CreateMarker';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rv.analytics.PlaybackMarker.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.rv.analytics.PlaybackMarker.EventCase = {
  EVENT_NOT_SET: 0,
  CREATE: 1
};

/**
 * @return {proto.rv.analytics.PlaybackMarker.EventCase}
 */
proto.rv.analytics.PlaybackMarker.prototype.getEventCase = function() {
  return /** @type {proto.rv.analytics.PlaybackMarker.EventCase} */(jspb.Message.computeOneofCase(this, proto.rv.analytics.PlaybackMarker.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.PlaybackMarker.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.PlaybackMarker.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.PlaybackMarker} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.PlaybackMarker.toObject = function(includeInstance, msg) {
  var f, obj = {
create: (f = msg.getCreate()) && proto.rv.analytics.PlaybackMarker.CreateMarker.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.PlaybackMarker}
 */
proto.rv.analytics.PlaybackMarker.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.PlaybackMarker;
  return proto.rv.analytics.PlaybackMarker.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.PlaybackMarker} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.PlaybackMarker}
 */
proto.rv.analytics.PlaybackMarker.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rv.analytics.PlaybackMarker.CreateMarker;
      reader.readMessage(value,proto.rv.analytics.PlaybackMarker.CreateMarker.deserializeBinaryFromReader);
      msg.setCreate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.PlaybackMarker.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.PlaybackMarker.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.PlaybackMarker} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.PlaybackMarker.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rv.analytics.PlaybackMarker.CreateMarker.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.analytics.PlaybackMarker.CreateMarker.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.analytics.PlaybackMarker.CreateMarker} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.toObject = function(includeInstance, msg) {
  var f, obj = {
location: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.analytics.PlaybackMarker.CreateMarker}
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.analytics.PlaybackMarker.CreateMarker;
  return proto.rv.analytics.PlaybackMarker.CreateMarker.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.analytics.PlaybackMarker.CreateMarker} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.analytics.PlaybackMarker.CreateMarker}
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.rv.analytics.PlaybackMarker.CreateMarker.Location} */ (reader.readEnum());
      msg.setLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.analytics.PlaybackMarker.CreateMarker.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.analytics.PlaybackMarker.CreateMarker} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocation();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.Location = {
  LOCATION_INSPECTOR: 0,
  LOCATION_SIDEBAR: 1
};

/**
 * optional Location location = 1;
 * @return {!proto.rv.analytics.PlaybackMarker.CreateMarker.Location}
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.prototype.getLocation = function() {
  return /** @type {!proto.rv.analytics.PlaybackMarker.CreateMarker.Location} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.rv.analytics.PlaybackMarker.CreateMarker.Location} value
 * @return {!proto.rv.analytics.PlaybackMarker.CreateMarker} returns this
 */
proto.rv.analytics.PlaybackMarker.CreateMarker.prototype.setLocation = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional CreateMarker create = 1;
 * @return {?proto.rv.analytics.PlaybackMarker.CreateMarker}
 */
proto.rv.analytics.PlaybackMarker.prototype.getCreate = function() {
  return /** @type{?proto.rv.analytics.PlaybackMarker.CreateMarker} */ (
    jspb.Message.getWrapperField(this, proto.rv.analytics.PlaybackMarker.CreateMarker, 1));
};


/**
 * @param {?proto.rv.analytics.PlaybackMarker.CreateMarker|undefined} value
 * @return {!proto.rv.analytics.PlaybackMarker} returns this
*/
proto.rv.analytics.PlaybackMarker.prototype.setCreate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.rv.analytics.PlaybackMarker.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rv.analytics.PlaybackMarker} returns this
 */
proto.rv.analytics.PlaybackMarker.prototype.clearCreate = function() {
  return this.setCreate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rv.analytics.PlaybackMarker.prototype.hasCreate = function() {
  return jspb.Message.getField(this, 1) != null;
};


