// source: proApiV1Timer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rv.data.API_v1_TimerFormat');
goog.provide('proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rv.data.API_v1_TimerFormat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rv.data.API_v1_TimerFormat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rv.data.API_v1_TimerFormat.displayName = 'proto.rv.data.API_v1_TimerFormat';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rv.data.API_v1_TimerFormat.prototype.toObject = function(opt_includeInstance) {
  return proto.rv.data.API_v1_TimerFormat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rv.data.API_v1_TimerFormat} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_TimerFormat.toObject = function(includeInstance, msg) {
  var f, obj = {
hour: jspb.Message.getFieldWithDefault(msg, 6, 0),
minute: jspb.Message.getFieldWithDefault(msg, 7, 0),
second: jspb.Message.getFieldWithDefault(msg, 8, 0),
millisecond: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rv.data.API_v1_TimerFormat}
 */
proto.rv.data.API_v1_TimerFormat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rv.data.API_v1_TimerFormat;
  return proto.rv.data.API_v1_TimerFormat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rv.data.API_v1_TimerFormat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rv.data.API_v1_TimerFormat}
 */
proto.rv.data.API_v1_TimerFormat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 6:
      var value = /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (reader.readEnum());
      msg.setHour(value);
      break;
    case 7:
      var value = /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (reader.readEnum());
      msg.setMinute(value);
      break;
    case 8:
      var value = /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (reader.readEnum());
      msg.setSecond(value);
      break;
    case 9:
      var value = /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (reader.readEnum());
      msg.setMillisecond(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rv.data.API_v1_TimerFormat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rv.data.API_v1_TimerFormat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rv.data.API_v1_TimerFormat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rv.data.API_v1_TimerFormat.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHour();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getMinute();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getSecond();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getMillisecond();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat = {
  NONE: 0,
  SHORT: 1,
  LONG: 2,
  REMOVE_SHORT: 3,
  REMOVE_LONG: 4
};

/**
 * optional API_v1_TimerUnitDisplayFormat hour = 6;
 * @return {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat}
 */
proto.rv.data.API_v1_TimerFormat.prototype.getHour = function() {
  return /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} value
 * @return {!proto.rv.data.API_v1_TimerFormat} returns this
 */
proto.rv.data.API_v1_TimerFormat.prototype.setHour = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional API_v1_TimerUnitDisplayFormat minute = 7;
 * @return {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat}
 */
proto.rv.data.API_v1_TimerFormat.prototype.getMinute = function() {
  return /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} value
 * @return {!proto.rv.data.API_v1_TimerFormat} returns this
 */
proto.rv.data.API_v1_TimerFormat.prototype.setMinute = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional API_v1_TimerUnitDisplayFormat second = 8;
 * @return {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat}
 */
proto.rv.data.API_v1_TimerFormat.prototype.getSecond = function() {
  return /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} value
 * @return {!proto.rv.data.API_v1_TimerFormat} returns this
 */
proto.rv.data.API_v1_TimerFormat.prototype.setSecond = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional API_v1_TimerUnitDisplayFormat millisecond = 9;
 * @return {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat}
 */
proto.rv.data.API_v1_TimerFormat.prototype.getMillisecond = function() {
  return /** @type {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.rv.data.API_v1_TimerFormat.API_v1_TimerUnitDisplayFormat} value
 * @return {!proto.rv.data.API_v1_TimerFormat} returns this
 */
proto.rv.data.API_v1_TimerFormat.prototype.setMillisecond = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


